---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  peco-backend
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: peco-cognito-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        UnusedAccountValidityDays: 365
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - AttributeDataType: String
          Name: orgId
          Mutable: true
        - AttributeDataType: String
          Name: apiKey
          Mutable: true
      # LambdaConfig:
      #   PostConfirmation: !GetAtt CognitoAutomaticOrgIdAssignmentFunction.Arn
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false

  # TODO delete this user pool when testing from CLI is not required anymore
  SampleUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      OpenApiVersion: 3.0.3
      ApiKeySourceType: HEADER
      Auth:
        AddApiKeyRequiredToCorsPreflight: true
        AddDefaultAuthorizerToCorsPreflight: true
        Authorizers:
          RestApiAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
        DefaultAuthorizer: RestApiAuthorizer
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: Default usage plan
          Description: Default usage plan with limited quota
          Quota:
            Limit: 1000
            Period: MONTH
          Throttle:
            BurstLimit: 10
            RateLimit: 1
      Models:
        tag:
          type: object
          additionalProperties: false
          required:
            - name
            - value
          properties:
            name:
              type: string
            value:
              type: string
        usecase:
          type: object
          additionalProperties: false
          required:
            - id
            - name
            - description
            - tags
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
            tags:
              type: array
              maxItems: 10
              items:
                $ref: tag

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction


  CommonLambdaDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: peco-common-lambda-dependencies-layer
      ContentUri: lib/.
      CompatibleRuntimes:
        - nodejs20.x

  GetUseCaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/use-case-crud.handle_get_request
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Layers:
        - !Ref CommonLambdaDependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UseCaseTable
      Environment:
        Variables:
          USE_CASE_TABLE_NAME: !Ref UseCaseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /use-cases/{id}
            Method: GET
            RestApiId: !Ref RestApi
            Auth:
              Authorizer: RestApiAuthorizer
              ApiKeyRequired: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - '@aws-sdk/client-api-gateway'
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
          - 'uuid'
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/use-case-crud.mts

  CreateUseCaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/use-case-crud.handle_post_request
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Layers:
        - !Ref CommonLambdaDependenciesLayer
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref UseCaseTable
      Environment:
        Variables:
          USE_CASE_TABLE_NAME: !Ref UseCaseTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /use-cases/
            Method: POST
            RestApiId: !Ref RestApi
            Auth:
              Authorizer: RestApiAuthorizer
              ApiKeyRequired: true
            RequestModel:
              Model: usecase
              Required: true
              ValidateBody: true
              ValidateParameters: false
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - '@aws-sdk/client-api-gateway'
          - '@aws-sdk/client-dynamodb'
          - '@aws-sdk/lib-dynamodb'
          - 'uuid'
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/use-case-crud.mts

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  UseCaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UseCase
      AttributeDefinitions:
        - AttributeName: orgId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: orgId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: Peco
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  UserPoolId:
    Description: Cognito UserPool ID
    Value: !Ref CognitoUserPool
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/use-cases/"
  ApiKey:
    Description: "You can find your API Key in the AWS console: (Put in the request HEADER as 'x-api-key')"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${RestApiApiKey}"
  SampleUserPoolClient:
    Description: "Cognito client id of a sample client created for testing purposes"
    Value: !Ref SampleUserPoolClient
